user:
  full_name:
    max_length: 50
  phone_number:
    max_length: 13
  avatar:
    max_size: 5
  per_page: 10
  hot_user:
    limit: 5
post:
  title:
    max_length: 100
  content:
    max_length: 3000
  per_page: 10
  max_tags: 10
tag:
  max_length: 20
  per_page: 10
  popular:
    limit: 15
comment:
  per_page: 10
